name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Create frontend config
        run: |
          mkdir -p _site
          cp -r *.html _site/ || true
          cp -r js _site/ || true
          cp -r css _site/ || true
          cp -r html _site/ || true
          
          echo "Creating frontend config..."
          cat > _site/config.js << 'EOF'
          window.BACKEND_URL = 'https://neuralmeet-backend.onrender.com';
          window.API_CONFIG = {
            baseURL: window.BACKEND_URL,
            timeout: 30000
          };
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
